services:
  db:
    image: mysql:8.0
    container_name: marmitatech-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marmitadb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Serviço 1 renomeado de "app" para "marmitatech-app" para evitar conflito
  marmitatech-app:
    image: kelvindsm/marmitatech-app:latest # <-- Corrigido para a imagem certa
    build: .
    container_name: marmitatech # <-- Corrigido para o nome certo (único)
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306  # <-- Corrigido para a porta interna do container
      DB_USER: user
      DB_PASS: password
      DB_NAME: marmitadb
    depends_on:
      db:
        condition: service_healthy
